language: android
android:
    components:
        - android-23
        - build-tools-23.0.1
        - platform-tools
        - extra

jdk: oraclejdk7

sudo: false

before_script:
    - chmod +x gradlew

script:
    - ./gradlew assembleDebug --stacktrace
