language: android
android:
    components:
        - tools
        - build-tools-15
        - android-15
        - platform-tools

    before_script:
        - chmod +x gradlew

    script:
            - ./gradlew assembleDebug --stacktrace
