language: android
android:
    components:
        - tools
        - build-tools-23
        - android-23
        - platform-tools

before_install:
    - chmod +x gradlew

script:
  - ./gradlew assembleDebug --stacktrace
