language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-15.1.0

    # The SDK version used to compile your project
    - android-15

    - platform-tools
